#!/bin/ksh

# a million different ways to do this

builtin() {
    i=0
    while read -r line; do    
        if [ "$i" -le "$3" ]; then
            if [ "$i" -ge "$2" ]; then
                printf "    $i\t%s\n" "$line"
            fi
        else 
            break
        fi
        i=$((i+1))
    done < "$1"
}


head_tail() {
    #line_count=$(wc -l "$1" | cut -d ' ' -f 1)
    head -n "$3" "$1" | tail -n "$(($3 + 1 - $2))"
}


cat_grep() {
    file="$1"
    for line in $(seq "$2" "$3"); do
        if [ "$line" -lt 10 ]; then 
            cat -n "$file" | grep "^     $line\t"
        else 
            cat -n "$file" | grep "^    $line\t"
        fi
    done
}

head_tail "$@"
