#!/bin/ksh

# a million different ways to do this

usage() { echo "Usage: $0 [-n] file from [to]" 1>&2; exit 1; }

tmp="/tmp/line_tmp"

while getopts ":n" o; do
    case "${o}" in
        n)
            numbers=1
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

builtin() {
    i=1
    while IFS= read -r line; do    
        if [ "$i" -le "$3" ]; then
            if [ "$i" -ge "$2" ]; then
                if [ -z "$numbers" ]; then
                    printf "%s\n" "$line"
                else
                    printf "    $i\t%s\n" "$line"
                fi
            fi
        else 
            break
        fi
        i=$((i+1))
    done < "$1"
}


head_tail() {
    head -n "$3" "$1" | tail -n "$(($3 + 1 - $2))"
}


cat_grep() {
    file="$1"
    for line in $(seq "$2" "$3"); do
        if [ "$line" -lt 10 ]; then 
            cat -n "$file" | grep "^     $line\t"
        else 
            cat -n "$file" | grep "^    $line\t"
        fi
    done
}

if [ ! -f "$1" ]; then
    cat > "$tmp"
    pipe=1
fi

if [ "$#" -eq 1 ]; then
    set -- "$tmp" "$1" "$1"
    builtin "$@"
elif [ "$#" -eq 2 ]; then
    if [ -f "$1" ]; then
        set -- "$1" "$2" "$2"
    else 
        set -- "$tmp" "$1" "$2"
    fi
    builtin "$@"
elif [ "$#" -eq 3 ]; then
    builtin "$@"
else
    usage
fi

if [ -n "$pipe" ]; then
    rm "$tmp"
fi
